export const MONSTER_NAMES = [
  "Squelette guerrier",
  "Gobelin des cryptes",
  "Spectre hurleur",
  "Araignee geante",
  "Zombie affame",
  "Goule putride",
  "Rat-garou",
  "Ombre vivante",
  "Chauve-souris vampire",
  "Garde fantome",
  "Slime acide",
  "Cultiste fou",
  "Loup des tenebres",
  "Serpent venimeux",
  "Mimic trompeur",
  "Banshee vengeresse",
  "Ogre brutal",
  "Elementaire de cendres",
  "Gargouille de pierre",
  "Necromancien dechu",
];
