export const ROOM_NAMES = [
  "Salle des torches eternelles",
  "Crypte abandonnee",
  "Bibliotheque poussiereuse",
  "Armurerie rouillee",
  "Chambre du gardien",
  "Salle du tresor vide",
  "Cuisine hantee",
  "Prison aux barreaux brises",
  "Chapelle profanee",
  "Laboratoire alchimique",
  "Salle du trône effondre",
  "Cave aux tonneaux",
  "Galerie des portraits",
  "Forge eteinte",
  "Salle des rituels",
  "Cachot humide",
  "Tour de guet",
  "Refectoire deserte",
  "Salle des gemmes",
  "Passage des ombres",
];
